conn sys/oracle AS SYSDBA;
GRANT EXECUTE ON utl_smtp TO PUBLIC;
grant execute on UTL_tcp to public;
disconnect;
conn system/oracle;
grant execute on MKS_AHORROS.FN_OBTIENE_NUMERO_VERIFICADOR to MKS_DATOS;
grant select, insert, update, delete, references on MKS_COMUNES.UBICACION_GEOGRAFICA to MKS_DATOS;
grant select, insert, update, delete, references on MKS_CONTABLES.COMPROBANTE to MKS_DATOS;
grant select, insert, update, delete, references on MKS_CONTABLES.ESTADO_COMPROBANTE to MKS_DATOS;
grant select, insert, update, delete, references on MKS_CONTABLES.TIPO_COMPROBANTE to MKS_DATOS;
grant select, insert, update, delete, references on MKS_CONTABLES.TIPO_COMPROBANTE_IFIP_AGENCIA to MKS_DATOS;
grant select, insert, update, delete, references on MKS_CONTABLES.CUENTAS_CUADRE_FINANCIERO to MKS_CONTABLES;
grant select, insert, update, delete, references on MKS_HISTORICOS.SALDO_DPF to MKS_CONTABLES; 
grant select, insert, update, delete, references on MKS_HISTORICOS.SALDOS_BOVEDA to MKS_CONTABLES; 
grant select, insert, update, delete, references on MKS_HISTORICOS.SALDOS_CUENTA to MKS_CONTABLES; 
grant select, insert, update, delete, references on MKS_IFIPS.IFIP to MKS_DATOS;
grant select, insert, update, delete, references on MKS_IFIPS.IFIP_AGENCIA to MKS_DATOS;
grant select, insert, update, delete, references on MKS_ADQUISICIONES.PAGO_COMPRA to MKS_DATOS;
grant select, insert, update, delete, references on MKS_SEGURIDADES.USUARIO to MKS_DATOS;
grant select, insert, update, delete, references on MKS_ESTRUCTURAS.UAF_CABECERA to MKS_DATOS;
grant select, insert, update, delete, references on MKS_ESTRUCTURAS.UAF_CLIENTE_DETALLE to MKS_DATOS;
grant select, insert, update, delete, references on MKS_ESTRUCTURAS.UAF_PRODUCTO_DETALLE to MKS_DATOS;
grant select, insert, update, delete, references on MKS_ESTRUCTURAS.UAF_TRANSACCION_DETALLE to MKS_DATOS;
grant select, insert, update, delete, references on MKS_HISTORICOS.TABLAS_CREDITOS to MKS_DATOS;
grant select, insert, update, delete, references on MKS_HISTORICOS.UAF_PERSONA_POLITICAMENTE_EXP to MKS_ESTRUCTURAS;
grant select, alter on MKS_ESTRUCTURAS.SEQ_CABECERA_UAF to MKS_DATOS;
grant execute on mks_comunes.pkg_ubicacion_geografica to MKS_ESTRUCTURAS;
grant execute on mks_contables.pkm_parametro_proceso_contable to MKS_ESTRUCTURAS;
grant execute on mks_contables.pkm_registro_contable to MKS_IFIPS;
grant execute on mks_cajas.pkm_ingreso_egreso_caja to MKS_IFIPS;
grant execute on mks_contables.pkm_cuenta_contable_con_dpf to MKS_PROCESOS_BATCH;
grant execute on mks_contables.pkm_registro_contable to MKS_PROCESOS_BATCH;
grant execute on mks_contables.pkg_tipo_plan_de_cuenta to MKS_PROCESOS_BATCH;
grant execute on MKS_CONTABLES.PKM_PARAMETRO_PROCESO_CONTABLE to MKS_PROCESOS_BATCH;
grant execute on mks_contables.pkg_periodo_contable to MKS_PROCESOS_BATCH;
grant execute on mks_contables.pkm_comprobante to MKS_PROCESOS_BATCH;
grant execute on mks_contables.pkg_comprobante to MKS_PROCESOS_BATCH;
grant execute on mks_contables.pkg_comprobante_detalle to MKS_PROCESOS_BATCH;
grant execute on mks_contables.pkg_registro_contable to MKS_PROCESOS_BATCH;
grant execute on mks_contables.pkm_perido_contable to MKS_PROCESOS_BATCH;
grant execute on mks_contables.pkg_periodo_contable to MKS_PROCESOS_BATCH;
grant execute on mks_comunes.f_quita_espacios_extra to MKS_HISTORICOS;
grant execute on mks_contables.pkm_parametro_proceso_contable to MKS_HISTORICOS;
grant execute on mks_contables.pkm_registro_contable to MKS_DPFS;
grant execute on mks_contables.pkm_parametro_proceso_contable to MKS_CREDITOS;
grant execute on mks_contables.pkm_registro_contable to MKS_CREDITOS;
grant execute on mks_contables.pkm_contabiliza_provision_car to MKS_CREDITOS;
grant execute on mks_cajas.pkm_ingreso_egreso_caja to MKS_CREDITOS;
grant execute on mks_contables.pkm_contab_pago_credito to MKS_CREDITOS;
grant execute on mks_cajas.pkm_ingreso_egreso_caja to MKS_CREDITOS;
grant execute on mks_cajas.pkm_ingreso_egreso_caja to MKS_CREDITOS;
grant execute on mks_procesos_batch.pka_credito to MKS_CREDITOS;
grant execute on mks_contables.pkm_contabiliza_castigo_car to MKS_CREDITOS;
grant execute on MKS_COMUNES.p_enviar_email to MKS_PROCESOS_BATCH;
grant execute on mks_comunes.f_quita_espacios_extra to MKS_ESTRUCTURAS;
grant execute on mks_contables.pkg_periodo_contable to MKS_ESTRUCTURAS;
grant execute on mks_contables.pkg_tipo_plan_de_cuenta to MKS_ESTRUCTURAS;
grant execute on mks_procesos_batch.pka_contables to MKS_CONTABLES;
grant execute on mks_contables.pkm_registro_contable to MKS_CAJAS;
grant execute on mks_contables.pkm_registro_contable to MKS_CAJAS;
grant execute on mks_contables.pkm_registro_contable to MKS_AHORROS;
grant execute on mks_cajas.pkm_saldos_caja to MKS_AHORROS;
grant execute on mks_cajas.pkg_apertura_caja_mov_cta to MKS_AHORROS;
grant execute on mks_seguros.pkg_contrato_seguro_dep to MKS_SEGUROS;
grant select, alter on mks_historicos.seq_reclasificacion_creditos to mks_historicos;
grant select, alter on mks_historicos.seq_reclasificacion_creditos to mks_creditos;